import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { classroomRoster } from '../src/classroom-profiles.js';
import { PRESETS } from '../src/config.js';
import { createAvatar } from '../src/avatar.js';
import { raiseClassroomHand } from '../src/classroom-poses.js';
import { Vector3 } from 'three';

const koreanRoster = classroomRoster('korean');
const students = koreanRoster.slice(0, 9);
assert.equal(students.filter(a => a.background === 'korean').length, 7);
assert.equal(students.filter(a => a.background === 'filipino').length, 1);
assert.equal(students.filter(a => a.background === 'white').length, 1);
assert.equal(students.filter(a => a.config.hairColor === '#211c1b').length, 8);
assert.ok(students.every(a => ['uniform', 'cardigan'].includes(a.config.shirt)));
assert.ok(classroomRoster('general')[0].config.headWidth < PRESETS[1].headWidth);
assert.ok(koreanRoster[0].config.headWidth < .96);
for (const config of [classroomRoster('general')[2].config, koreanRoster[6].config]) {
  const avatar = createAvatar(config, { tpose: true });
  try {
    avatar.pose('sit'); raiseClassroomHand(avatar); avatar.group.updateMatrixWorld(true);
    const position = name => avatar.boneMap[name].getWorldPosition(new Vector3());
    const wrist = position('RightHand'), elbow = position('RightLowerArm'), shoulder = position('RightUpperArm');
    assert.ok(elbow.y < wrist.y - .1, 'The forearm must rise from a bent elbow.');
    assert.ok(wrist.y > shoulder.y + .15, 'The hand must be raised above the shoulder.');
    assert.ok(Math.abs(wrist.x - position('Head').x) > .32, 'The raised hand must clear the face.');
  } finally { avatar.dispose(); }
}

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('test-results', { recursive: true });
try {
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173');
  await page.waitForFunction(() => window.avatarStudio);
  await page.locator('#avatar-name').fill('교실 전환 확인');
  await page.locator('#avatar-name').press('Tab');
  const original = await page.evaluate(() => window.avatarStudio.getConfig());
  await page.locator('#classroom-tab').click();
  // Switching away during preparation must not steal the studio's canvas later.
  await page.locator('#studio-tab').click();
  await page.waitForFunction(() => window.avatarStudio.getClassroomStats(), {}, { timeout: 120000 });
  assert.equal(await page.locator('#viewport > canvas').count(), 1);
  assert.equal(await page.locator('#studio-panel').isVisible(), true);
  await page.locator('#classroom-tab').click();
  await page.waitForTimeout(300);
  const stats = await page.evaluate(() => window.avatarStudio.getClassroomStats());
  assert.equal(stats.avatars, 10);
  assert.equal(stats.students, 9);
  assert.equal(stats.teachers, 1);
  assert.equal(stats.poses.length, 5);
  assert.equal(stats.context, 'korean');
  assert.equal(stats.occupants[4].background, 'filipino');
  assert.equal(stats.occupants[5].background, 'white');
  assert.equal(await page.locator('#classroom-viewport button, #classroom-viewport input, #classroom-viewport select').count(), 0);
  assert.equal(await page.locator('#studio-panel').isVisible(), false);
  assert.equal(await page.locator('.header-actions').isVisible(), false);
  const bounds = await page.locator('#classroom-viewport').boundingBox();
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 130, bounds.y + bounds.height / 2 + 15, { steps: 8 }); await page.mouse.up();
  await page.waitForTimeout(300);
  assert.notDeepEqual((await page.evaluate(() => window.avatarStudio.getClassroomStats())).camera, stats.camera);
  await page.mouse.wheel(0, -400);
  await page.waitForTimeout(300);
  assert.ok((await page.evaluate(() => window.avatarStudio.getClassroomStats())).zoom > stats.zoom);
  await page.locator('#classroom-reset').click();
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).zoom, 1);
  await page.locator('#classroom-zoom-in').click();
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).zoom, 1.2);
  await page.locator('#classroom-zoom-out').click();
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).zoom, 1);
  const pixels = async () => createHash('sha256').update(await page.locator('#classroom-viewport canvas').evaluate(canvas => canvas.toDataURL())).digest('hex');
  const movingFrame = await pixels();
  await page.waitForTimeout(700);
  assert.notEqual(await pixels(), movingFrame, 'The classroom should animate automatically.');
  await page.locator('[data-scenario=break]').click();
  await page.waitForTimeout(300);
  const breakStats = await page.evaluate(() => window.avatarStudio.getClassroomStats());
  assert.equal(breakStats.scenario, 'break');
  assert.equal(breakStats.occupants.filter(a => a.mode === 'chat').length, 4);
  assert.equal(breakStats.occupants.filter(a => a.mode === 'walk').length, 2);
  await page.waitForTimeout(2000);
  const later = await page.evaluate(() => window.avatarStudio.getClassroomStats());
  for (const i of [6, 7]) assert.notDeepEqual(later.occupants[i].position, breakStats.occupants[i].position, 'Walkers must move through the room.');
  assert.deepEqual(later.occupants[4].position, breakStats.occupants[4].position);
  await page.screenshot({ path: 'test-results/classroom-break.png' });
  await page.locator('[data-scenario=lesson]').click();
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).scenario, 'lesson');
  assert.deepEqual((await page.evaluate(() => window.avatarStudio.getClassroomStats())).occupants.map(a => a.position), stats.occupants.map(a => a.position));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForTimeout(2500);
  const stillFrame = await pixels();
  await page.waitForTimeout(400);
  assert.equal(await pixels(), stillFrame, 'Reduced-motion preferences should produce a still scene.');
  await page.screenshot({ path: 'test-results/classroom-desktop.png' });
  await page.locator('[data-scenario=break]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(300);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  assert.equal(await page.locator('#classroom-viewport canvas').isVisible(), true);
  await page.screenshot({ path: 'test-results/classroom-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 720 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#classroom-tab').focus();
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#studio-tab').getAttribute('aria-selected'), 'true');
  assert.equal(await page.locator('#viewport > canvas').count(), 1);
  assert.deepEqual(await page.evaluate(() => window.avatarStudio.getConfig()), original);
  assert.equal(await page.locator('#avatar-name').inputValue(), original.name);
  await page.locator('[data-tab=expression]').click();
  await page.locator('[data-choice=angry]').click();
  assert.equal(await page.evaluate(() => window.avatarStudio.getConfig().expression), 'angry');
  await page.locator('#undo').click();
  assert.equal(await page.evaluate(() => window.avatarStudio.getConfig().expression), original.expression);
  await page.locator('#classroom-tab').click();
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).avatars, 10);
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).scenario, 'break');
  assert.equal(await page.locator('#classroom-viewport > canvas').count(), 1);
  const preserved = await page.evaluate(() => window.avatarStudio.getClassroomStats());
  await page.locator('[data-classroom-context=general]').click();
  await page.waitForFunction(() => window.avatarStudio.getClassroomStats().context === 'general', {}, { timeout: 120000 });
  assert.equal((await page.evaluate(() => window.avatarStudio.getClassroomStats())).scenario, 'break');
  await page.locator('[data-classroom-context=korean]').click();
  await page.waitForFunction(() => window.avatarStudio.getClassroomStats().context === 'korean', {}, { timeout: 120000 });
  const restored = await page.evaluate(() => window.avatarStudio.getClassroomStats());
  assert.equal(restored.scenario, 'break');
  assert.equal(restored.zoom, preserved.zoom);
  restored.camera.forEach((v, i) => assert.ok(Math.abs(v - preserved.camera[i]) < .0001));
  assert.deepEqual(restored.occupants.map(a => a.name), preserved.occupants.map(a => a.name));
  assert.equal(restored.occupants.filter(a => a.role === 'student' && a.background === 'filipino').length, 1);
  assert.equal(restored.occupants.filter(a => a.role === 'student' && a.background === 'white').length, 1);
  assert.deepEqual(await page.evaluate(() => window.avatarStudio.getConfig()), original);
  await page.screenshot({ path: 'test-results/classroom-korean-break.png' });
  assert.deepEqual(errors, []);
  console.log('PASS: classroom rendering, orbit and zoom, lessons and breaks, walking and talking, reduced motion, mobile layout, repeated tabs, studio settings and undo.');
} finally {
  await browser.close();
}
